# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dustin Parker's Blog
email: adamdustinparker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts and insights as I traverse the world of web development, technology, and anything else I feel like talking about.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://walkerofthesky.github.io/" # the base hostname & protocol for your site
twitter_username: aDustinParker
github_username:  walkerofthesky

# Build settings
markdown: kramdown
permalink: /articles/:title

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "page"
